"""added area_atuacao and many to many relationship with concurso

Revision ID: 0853b75fce51
Revises: db3f41183d17
Create Date: 2025-11-28 16:20:44.783420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0853b75fce51'
down_revision: Union[str, Sequence[str], None] = 'db3f41183d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area_atuacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concurso_area_atuacao',
    sa.Column('area_atuacao_id', sa.Integer(), nullable=False),
    sa.Column('concurso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_atuacao_id'], ['area_atuacao.id'], ),
    sa.ForeignKeyConstraint(['concurso_id'], ['concurso.id'], ),
    sa.PrimaryKeyConstraint('area_atuacao_id', 'concurso_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concurso_area_atuacao')
    op.drop_table('area_atuacao')
    # ### end Alembic commands ###
