"""Remove campos nivel e area_atuacao

Revision ID: 427762e5a62e
Revises: e69aee3c1c8c
Create Date: 2026-05-18 21:01:32.163347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427762e5a62e'
down_revision: Union[str, Sequence[str], None] = 'e69aee3c1c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concurso', 'area_atuacao')
    op.drop_column('concurso', 'nivel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concurso', sa.Column('nivel', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('concurso', sa.Column('area_atuacao', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
