"""updated null constraints on concurso table

Revision ID: 71a05fced265
Revises: af4318cba7e0
Create Date: 2025-11-21 22:13:02.980432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '71a05fced265'
down_revision: Union[str, Sequence[str], None] = 'af4318cba7e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concurso', 'vagas',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('concurso', 'salario_max',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('concurso', 'inscricao_ate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('concurso', 'inscricao_ate',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('concurso', 'salario_max',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('concurso', 'vagas',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
