"""Adicionado campos string para nivel e area_atuacao

Revision ID: 9654e5d7a4aa
Revises: 0853b75fce51
Create Date: 2026-05-16 14:55:10.483098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9654e5d7a4aa'
down_revision: Union[str, Sequence[str], None] = '0853b75fce51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concurso', sa.Column('nivel', sa.String(), nullable=False))
    op.add_column('concurso', sa.Column('area_atuacao', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concurso', 'area_atuacao')
    op.drop_column('concurso', 'nivel')
    # ### end Alembic commands ###
