"""added regiao column to concursos

Revision ID: af4318cba7e0
Revises: a2933087a696
Create Date: 2025-11-21 22:06:30.004041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af4318cba7e0'
down_revision: Union[str, Sequence[str], None] = 'a2933087a696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concurso', sa.Column('regiao', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concurso', 'regiao')
    # ### end Alembic commands ###
