"""added field for timestamp of creation

Revision ID: db3f41183d17
Revises: 71a05fced265
Create Date: 2025-11-25 14:32:56.819563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3f41183d17'
down_revision: Union[str, Sequence[str], None] = '71a05fced265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concurso', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concurso', 'created_at')
    # ### end Alembic commands ###
