"""Adiciona campo de URL para PDF do edital de abertura

Revision ID: e59f36e322ab
Revises: 427762e5a62e
Create Date: 2026-05-20 02:03:26.830708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59f36e322ab'
down_revision: Union[str, Sequence[str], None] = '427762e5a62e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concurso', sa.Column('edital_pdf_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concurso', 'edital_pdf_url')
    # ### end Alembic commands ###
