"""adicionado tabelas de nivel de escolaridade e area de atuação

Revision ID: e69aee3c1c8c
Revises: 9654e5d7a4aa
Create Date: 2026-05-18 20:23:15.982722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e69aee3c1c8c'
down_revision: Union[str, Sequence[str], None] = '9654e5d7a4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nivel_escolaridade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concurso_nivel_escolaridade',
    sa.Column('nivel_escolaridade_id', sa.Integer(), nullable=False),
    sa.Column('concurso_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concurso_id'], ['concurso.id'], ),
    sa.ForeignKeyConstraint(['nivel_escolaridade_id'], ['nivel_escolaridade.id'], ),
    sa.PrimaryKeyConstraint('nivel_escolaridade_id', 'concurso_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concurso_nivel_escolaridade')
    op.drop_table('nivel_escolaridade')
    # ### end Alembic commands ###
